
ipc    = false
splash = false

wallpaper {
	monitor =
	path = ~/.config/hypr/assets/gruvbox15.png
}

wallpaper {
	monitor = DP-1
	path = ~/.config/hypr/assets/55495845-linux-ubuntu-anime-girls.png
}
