
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?* ; do
		[ -x "$f" ] && . $f
	done
fi

for f in  $XDG_CONFIG_HOME/X11/xinitrc.d/?*; do
	$f
done
unset f

# -- Launch Applications --
{
	sleep 3
	$BROWSER >/dev/null 2>&1 &
	$TERMINAL -c ncmpcpp    -e ncmpcpp &
	$TERMINAL -c mutt       -e mutt &
	$TERMINAL -c calcurse   -e calcurse &
	$TERMINAL -c newsboat   -e newsboat &
} &


exec wm

# vim:ft=sh
