
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?* ; do
		[ -x "$f" ] && . $f
	done
fi

{
	sleep 3

	# -- setup

	for f in  $XDG_CONFIG_HOME/X11/xinitrc.d/?*; do
		$f
	done
	unset f

	# -- Launch Applications --

	$BROWSER >/dev/null 2>&1 &
	$TERMINAL -n ncmpcpp    -e ncmpcpp &
	$TERMINAL -n mutt       -e mutt &
	$TERMINAL -n calcurse   -e calcurse &
	$TERMINAL -n newsboat   -e newsboat &
} &


exec wm

# vim:ft=sh
