
$border_size = 5
$gaps_out = 0

windowrule = match:fullscreen_state_client 1, rounding 0, border_size 2, opacity 1.0 override

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1],   gapsout:0, gapsin:0
windowrule = match:float off, match:workspace w[tv1], border_size 0, rounding 0
windowrule = match:float off, match:workspace f[1],   border_size 0, rounding 0


general {
	border_size = $border_size
	gaps_in = -$border_size,0,0,-$border_size
	gaps_out = $gaps_out

	col.active_border         = rgba(9d0006FF) rgba(9d0006FF) rgba(9d0006FF) rgba(FFFFFF60) 90deg
	col.inactive_border       = rgba(FFFFFF00)
	
	layout = dwindle

	snap {
		enabled = true
	}
}


decoration {
	rounding = 10
	rounding_power = 3

	#active_opacity   = 1.00
	#inactive_opacity = 0.85

	#dim_inactive = true
	#dim_modal    = true
	#dim_strength = 0.10

	shadow {
		enabled = true
		range          = 8
		render_power   = 3
		color          = rgba(555555AA)
		color_inactive = rgba(555555AA)
		offset         = 1, 3
	}
}

dwindle {
	force_split        = 2
	preserve_split     = true
	precise_mouse_move = true
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	force_default_wallpaper = 2
	on_focus_under_fullscreen = 1

	animate_manual_resizes = false

	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
}

ecosystem {
	no_update_news = true
}

