clear_all_shortcuts yes

kitty_mod alt

map kitty_mod+F5 load_config_file
map F11 toggle_fullscreen

map shift+insert   paste_from_selection

# TAB
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9

map kitty_mod+KP_1 goto_tab 1
map kitty_mod+KP_2 goto_tab 2
map kitty_mod+KP_3 goto_tab 3
map kitty_mod+KP_4 goto_tab 4
map kitty_mod+KP_5 goto_tab 5
map kitty_mod+KP_6 goto_tab 6
map kitty_mod+KP_7 goto_tab 7
map kitty_mod+KP_8 goto_tab 8
map kitty_mod+KP_9 goto_tab 9

map kitty_mod+shift+t new_tab
map kitty_mod+shift+w close_tab

map kitty_mod+tab       next_tab
map kitty_mod+shift+tab previous_tab

map kitty_mod+right next_tab
map kitty_mod+left  previous_tab

map kitty_mod+shift+n move_tab_backward
map kitty_mod+shift+r move_tab_forward


# LAYOUT

# focus window
map kitty_mod+n neighboring_window left
map kitty_mod+r neighboring_window down
map kitty_mod+t neighboring_window up
map kitty_mod+d neighboring_window right

map kitty_mod+enter launch --location=split

map --new-mode=mw --timeout=2 kitty_mod+space

	map --mode=mw kitty_mod+n launch --location=before
	map --mode=mw kitty_mod+r launch --location=hsplit
	# FIXME: How to create window above?
	map --mode=mw kitty_mod+t launch --location=hsplit
	map --mode=mw kitty_mod+d launch --location=after


	map --mode=mw h resize_window wider    25
	map --mode=mw g resize_window shorter  10
	map --mode=mw f resize_window taller   10
	map --mode=mw q resize_window narrower 25

	map --mode=mw n move_window left
	map --mode=mw r move_window down
	map --mode=mw t move_window up
	map --mode=mw d move_window right

	map --mode=mw m      resize_window wider    25
	map --mode=mw comma  resize_window shorter  10
	map --mode=mw period resize_window taller   10
	map --mode=mw j      resize_window narrower 25

	map --mode=mw x       close_window_with_confirmation
	map --mode=mw shift+x close_window



# Navigation
map ctrl+home      scroll_home
map ctrl+end       scroll_end

map page_up        scroll_page_up
map page_down      scroll_page_down

map kitty_mod+up    scroll_to_prompt -1
map kitty_mod+down  scroll_to_prompt +1

# no mouse wheel events for zoom
#     https://github.com/kovidgoyal/kitty/issues/3959
map kitty_mod+equal change_font_size all 0
map kitty_mod+plus  change_font_size all +2.0
map kitty_mod+minus change_font_size all -2.0


