update_check_interval 0



# FONT
font_size 13
disable_ligatures cursor
#font_features +calt +ss19 +ss01

#font_family      Cascadia Code NF SemiLight
#bold_font        Cascadia Code NF Bold
#italic_font      Cascadia Code NF SemiLight Italic
#bold_italic_font Cascadia Code NF Bold Italic

font_family      family='Cascadia Code NF' style=Regular          variable_name=CascadiaCodeNFRoman features='      +ss19'
bold_font        family='Cascadia Code NF' style=Bold               variable_name=CascadiaCodeNFRoman features='      +ss19'
italic_font      family='Cascadia Code NF' style='Regular Italic' variable_name=''                  features='+ss01 +ss19'
bold_italic_font family='Cascadia Code NF' style='Bold Italic'      variable_name=''                  features='+ss01 +ss19'


shell_integration no-cursor

cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2
cursor_blink_interval 0.8
cursor_stop_blinking_after 8.0

detect_urls yes
underline_hyperlinks always
url_style double

# Mouse
default_pointer_shape arrow
mouse_hide_wait 0

copy_on_select yes
strip_trailing_spaces smart


# Window Layout
enabled_layouts splits
remember_window_size  no

window_border_width 2pt

window_margin_width 3


# Text cursor

cursor_trail 1
cursor_trail_decay 0.1 0.25
cursor_trail_start_threshold 20


# Performance
scrollback_lines 500
clipboard_max_size 5


# Terminal bell
enable_audio_bell no
visual_bell_duration 0.15 linear


# TAB BAR
tab_bar_edge top
tab_bar_style separator
tab_separator ""
active_tab_title_template " {index} ▏{title} "
tab_title_template " {index} ▏{title} "



include keybindings.conf
