
# -- Monitor Setup --
xrandr --output $MONITOR0 --auto --primary --output $MONITOR1 --auto --left-of $MONITOR0


# -- Keyboard Layout --
setxkbmap -layout de -variant neo -option altwin:swap_lalt_lwin


# -- Background --
feh --no-fehbg --bg-fill $HOME/Pictures/wallpapers/current


# -- Misc X --
test -f $XDG_CONFIG_HOME/X11/xresources && xrdb -merge $_
test -f $XDG_CONFIG_HOME/X11/xmodmap    && xmodmap    $_


# -- systemd: set DISPLAY and XAUTHORITY --
test -f /etc/X11/xinit/xinitrc.d/50-systemd-user.sh && . $_


# -- Mouse Cursor --
xsetroot -cursor_name left_ptr


# -- Disable DPMS --
xset -dpms
xset s noblank
xset s off


# -- Smart screenlock --
#xautolock -corners +-+- -cornerredelay 30 -locker 'slock & sleep 1 ; xset dpms force off' &


# -- Launch Applications --
{
	sleep 3
	$BROWSER &
	$TERMINAL -n ncmpcpp    -e ncmpcpp &
	$TERMINAL -n neomutt    -e $SHELL -c neomutt &
	$TERMINAL -n calcurse   -e calcurse $xdg_calcurse &
	$TERMINAL -n newsboat   -e newsboat &
} &


# -- Start WM --

case $1 in
	herbstluftwm )
		sxhkd -m -1 $XDG_CONFIG_HOME/herbstluftwm/sxhkdrc &
		exec herbstluftwm --locked
		;;
	* )
		sxhkd -m -1 $XDG_CONFIG_HOME/bspwm/sxhkdrc &
		exec bspwm
		;;
esac


# vim:ft=sh
