
# -- Keyboard Layout --
setxkbmap -layout de -variant neo -option
#setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl -option caps:swapescape,eurosign:e


# -- Background --
feh --no-fehbg --bg-tile $HOME/Pictures/wallpapers/current


# -- Misc X --
test -f $XDG_CONFIG_HOME/X11/xresources && xrdb -load $_
test -f $XDG_CONFIG_HOME/X11/xmodmap    && xmodmap    $_


# -- systemd: set DISPLAY and XAUTHORITY --
test -f /etc/X11/xinit/xinitrc.d/50-systemd-user.sh && source $_


# -- Disable DPMS --
xset -dpms
xset s noblank
xset s off


# -- Smart screenlock --
#xautolock -corners +-+- -cornerredelay 30 -locker 'slock & sleep 1 ; xset dpms force off' &


# -- Launch Applications --
{
	sleep 3
	$BROWSER &
	$TERMINAL -n ncmpcpp    -e ncmpcpp &
	$TERMINAL -n mutt       -e zsh -c mutt -n &
	$TERMINAL -n calcurse   -e calcurse $xdg_calcurse &
	$TERMINAL -n newsbeuter -e newsbeuter &
} &

sxhkd &

# -- Start WM --
exec herbstluftwm --locked

# vim:ft=sh
