#! /bin/sh


# -- Monitor Settings --
xrandr --output HDMI-1 --auto --left-of DVI-I-1 --output DVI-I-1 --primary --auto


# -- Keyboard Layout --
setxkbmap -layout de -variant neo -option
#setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl -option caps:swapescape,eurosign:e


# -- Mouse Cursor --
xsetroot -cursor_name left_ptr -bg red -fg black


# -- Background --
feh --no-fehbg --bg-tile $HOME/Pictures/wallpapers/ds_anime1.jpg


# -- Misc X --
test -f $XDG_CONFIG_HOME/X11/xresources && xrdb -load $_
test -f $XDG_CONFIG_HOME/X11/xmodmap    && xmodmap    $_


# -- systemd: set DISPLAY and XAUTHORITY --
test -f /etc/X11/xinit/xinitrc.d/50-systemd-user.sh && source $_


# -- Start gpg-agent etc. --
gpg-connect-agent /bye > /dev/null 2>&1


# -- Disable DPMS --
xset -dpms
xset s noblank
xset s off


# -- Smart screenlock --
#xautolock -corners +-+- -cornerredelay 30 -locker 'slock & sleep 1 ; xset dpms force off' &

# Move mouse to the right Screen
swarp 3000 0


# -- Launch Applications --
test ! -f $XDG_CONFIG_HOME/mpd/pid && mpd

( sleep  3; firefox ) &
( sleep 10; st -n ncmpcpp    -e ncmpcpp                ) &
( sleep 10; st -n mutt       -e mutt -n                ) &
( sleep 10; st -n calcurse   -e calcurse $xdg_calcurse ) &
( sleep 10; st -n newsbeuter -e newsbeuter             ) &


# -- Start WM --
exec herbstluftwm --locked
#exec xmonad
#exec i3

