#!/usr/bin/env sh

# At first start, each monitors only contains the "default" desktop
# Creates desktops only on initial setup.
if [ $(bspc query -D | wc -l) -eq $(bspc query -M | wc -l) ]; then
	bspc monitor $MONITOR0 -d 1 3 4 5 6 7 8 9 0
	bspc monitor $MONITOR1 -d 2
fi

bspc config normal_border_color   '#ffffff'
bspc config active_border_color   '#3333cc'
bspc config focused_border_color  '#ff0000'
bspc config presel_feedback_color '#E1505A'

window_gap=7
side_padding=0

bspc config border_width            5
bspc config window_gap              $window_gap
for side in top right bottom left; do
	bspc config ${side}_padding $((${side_padding}-${window_gap}))
done

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config initial_polarity        first_child
bspc config pointer_modifier        mod4
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true

bspc rule -r *:*
bspc rule -a Pinentry  state=floating
bspc rule -a discord         desktop=8
bspc rule -a *:mutt          desktop=9
bspc rule -a *:neomutt       desktop=9
bspc rule -a *:ncmpcpp       desktop=0
bspc rule -a *:calcurse      desktop=0
bspc rule -a *:newsboat      desktop=0
# Libreoffice 5.x starts with Soffice and changes it after launch... WTF?
bspc rule -a Soffice         state=tiled
bspc rule -a *:libreoffice   state=tiled
bspc rule -a Zathura         state=tiled
bspc rule -a Pavucontrol     state=floating
bspc rule -a *:scratchpad    state=floating

panel=$XDG_CONFIG_HOME/polybar/startup
[ -x "$panel" ] && $panel bspwm-desktop-top &

compton=$XDG_CONFIG_HOME/bspwm/compton.conf
[ ! $(pgrep -x compton) ] && [ -f "$compton" ] && compton --config $compton &

