#! /bin/sh

bspc monitor $MONITOR0 -d 1 3 4 5 6 7 8 9 0
bspc monitor $MONITOR1 -d 2

bspc config normal_border_color   '#ffffff'
bspc config active_border_color   '#3333cc'
bspc config focused_border_color  '#ff0000'
bspc config presel_feedback_color '#073642'

bspc config border_width            5
bspc config window_gap              15

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         true
for side in top right bottom left; do
	bspc config ${side}_padding -5
done

bspc config pointer_modifier        mod4
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true

bspc rule -r *:*
bspc rule -a Pinentry-gtk-2  state=floating
bspc rule -a Firefox         desktop=1
bspc rule -a discord         desktop=8
bspc rule -a *:mutt          desktop=9
bspc rule -a *:ncmpcpp       desktop=0
bspc rule -a *:calcurse      desktop=0
bspc rule -a *:newsbeuter    desktop=0
# Libreoffice 5.x starts with Soffice and changes it after launch... WTF?
bspc rule -a Soffice         state=tiled
bspc rule -a *:libreoffice   state=tiled
bspc rule -a Zathura         state=tiled

panel=$XDG_CONFIG_HOME/bspwm/panel.sh
[ -x "$panel" ] && $panel &

compton=$XDG_CONFIG_HOME/bspwm/compton.conf
[ ! $(pgrep compton) ] && [ -f "$compton" ] && compton --config $compton &

