#!/usr/bin/env sh

# At first start, each monitors only contains the "default" desktop
# Creates desktops only on initial setup.
if [ $(bspc query -D | wc -l) -eq $(bspc query -M | wc -l) ]; then
	bspc monitor $primonitor -d 1 3 4 5 8 9 10
	bspc monitor $secmonitor -d 2
fi

bspc config focused_border_color        '#073642'
bspc config active_border_color         '#AAB7B7'
bspc config normal_border_color         '#FDF6E3'
bspc config presel_feedback_color       '#93A1A1'

bspc config border_width                1
bspc config window_gap                  9
bspc config top_padding                -3
bspc config left_padding               -6
bspc config bottom_padding              3
bspc config right_padding               3

bspc config split_ratio                 0.5
bspc config single_monocle              false
bspc config borderless_monocle          false
bspc config gapless_monocle             false
bspc config paddingless_monocle         false
bspc config initial_polarity            first_child
bspc config pointer_modifier            mod4
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     true
bspc config click_to_focus              any
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config ignore_ewmh_focus           true

bspc config external_rules_command      "$XDG_CONFIG_HOME/bspwm/external_rules"

bspc rule -r '*:*'
bspc rule -a 'Pinentry'                 state=floating
bspc rule -a 'discord'                  desktop=8
bspc rule -a 'mutt'                     desktop=9
bspc rule -a 'neomutt'                  desktop=9
bspc rule -a 'ncmpcpp'                  desktop=10
bspc rule -a 'calcurse'                 desktop=10
bspc rule -a 'newsboat'                 desktop=10
bspc rule -a 'Zathura'                  state=tiled
bspc rule -a 'Pavucontrol'              state=floating
bspc rule -a 'scratchpad'               state=floating

