#!/bin/bash

wid="$1"
class="$2"
instance="$3"

case $class in
	Soffice | libreoffice)
		case $(xprop -id $wid _NET_WM_WINDOW_TYPE) in
			*_NET_WM_WINDOW_TYPE_NORMAL* ) echo "state=tiled" ;;
		esac
		;;
esac

