background              #fbf1c7
foreground              #3c3836

url_color               #458588

selection_foreground    #3c3836
selection_background    #d65d0e

color0                  #ebdbb2
color1                  #cc241d
color2                  #98971a
color3                  #d79921
color4                  #458588
color5                  #b16286
color6                  #689d6a
color7                  #7c6f64
color8                  #928374
color9                  #9d0006
color10                 #79740e
color11                 #b57614
color12                 #076678
color13                 #8f3f71
color14                 #427b58
color15                 #282828

cursor                  #665c54
cursor_text_color       #bdae93

mark1_background        #458588
mark1_foreground        #ebdbb2
mark2_background        #689d6a
mark2_foreground        #ebdbb2
mark3_background        #b16286
mark3_foreground        #ebdbb2

tab_bar_background      #a89984
tab_bar_margin_color    #a89984
active_tab_background   #fbf1c7
active_tab_foreground   #3c3836
inactive_tab_background #ebdbb2
inactive_tab_foreground #7c6964

active_border_color     #458588
inactive_border_color   #ebdbb2
bell_border_color       #d65d0e

visual_bell_color       #d65d0e
