#!/usr/bin/env sh

if [[ "$1" != 'update' ]]; then
	bspwm-desktops 1 2 3 4 5 8 9 10
fi

bspc config focused_border_color        '#657B83'
bspc config active_border_color         '#AAB7B7'
bspc config normal_border_color         '#FDF6E3'
bspc config presel_feedback_color       '#93A1A1'

bspc config border_width                1
bspc config window_gap                  8
bspc config top_padding                -5
bspc config left_padding               -5
bspc config bottom_padding             -1
bspc config right_padding              -1

bspc config bottom_monocle_padding     -4
bspc config right_monocle_padding      -4

bspc config split_ratio                 0.5
bspc config initial_polarity            first_child
bspc config pointer_modifier            mod4
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config click_to_focus              any
bspc config removal_adjustment          true
bspc config single_monocle              true
bspc config ignore_ewmh_focus           true

bspc config external_rules_command      "$(which bspwm-external_rules)"

bspc rule -r '*:*'
bspc rule -a 'Pinentry'                 state=floating
bspc rule -a 'discord'                  desktop=8
bspc rule -a 'mutt'                     desktop=9
bspc rule -a 'neomutt'                  desktop=9
bspc rule -a 'ncmpcpp'                  desktop=10
bspc rule -a 'calcurse'                 desktop=10
bspc rule -a 'newsboat'                 desktop=10
bspc rule -a 'Zathura'                  state=tiled
bspc rule -a 'Pavucontrol'              state=floating
bspc rule -a 'Lxappearance'             state=floating rectangle=950x600+0+0 center=on
bspc rule -a 'scratchpad'               state=floating

bspwm-panel "$(bspc query -M -m primary --names)" &

