#!/usr/bin/env sh


# -- General --

bspc config focused_border_color        '#657B83'
bspc config active_border_color         '#AAB7B7'
bspc config normal_border_color         '#FDF6E3'
bspc config presel_feedback_color       '#93A1A1'

bspc config border_width                1
bspc config window_gap                  8
bspc config top_padding                -5
bspc config left_padding               -5
bspc config bottom_padding             -1
bspc config right_padding              -1

bspc config bottom_monocle_padding     -4
bspc config right_monocle_padding      -4

[ $(bspc query -M | wc -l) -le 1 ] &&
	bspc config borderless_monocle true

bspc config split_ratio                 0.46
bspc config initial_polarity            second_child
bspc config pointer_modifier            mod4
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config click_to_focus              any
bspc config removal_adjustment          true
bspc config single_monocle              true
bspc config ignore_ewmh_focus           true
bspc config directional_focus_tightness low


primon="$(bspc query -M -m primary)"
secmons=( "$(bspc query -M | sed "/$primon/d")" )

if [ "$1" -eq 0 ]; then
	bspwm-desktops 1 2 3 4 5 8 9 10 -m "$primon" "${secmons[@]}"
	wmname LG3D
fi


# -- Rules --

# - WM_CLASS = "class", "instance"
# - WM_NAME = "title"
# bspc rule -a 'instance:class:title'

[ "$1" -eq 0 ] && bspawn rm '*'
bspc config external_rules_command      "$(which bspwm-external_rules)"

bspc rule -r '*:*'
bspc rule -a 'Pinentry'                 state=floating sticky=on
bspc rule -a 'discord'                  desktop=8
bspc rule -a 'St:mutt'                  desktop=9
bspc rule -a 'St:neomutt'               desktop=9
bspc rule -a 'St:ncmpcpp'               desktop=10
bspc rule -a 'St:calcurse'              desktop=10
bspc rule -a 'St:newsboat'              desktop=10
bspc rule -a 'Zathura'                  state=tiled
bspc rule -a 'Pavucontrol'              state=floating
bspc rule -a 'Lxappearance'             state=floating rectangle=950x600+0+0 center=on
bspc rule -a 'St:scratchpad'            state=floating center=on
bspc rule -a 'St:float'                 state=floating center=on
bspc rule -a 'mpv:gl'                   border=off
bspc rule -a 'Eclipse:Eclipse'          desktop=2
bspc rule -a 'jetbrains-idea:jetbrains-idea' desktop=2
bspc rule -a 'DBeaver'                  desktop=4
bspc rule -a 'TeamSpeak 3'              desktop=8
bspc rule -a 'Signal:signal'            desktop=8
bspc rule -a 'firefox:Browser'          state=floating
bspc rule -a 'Steam:Steam'              state=floating
bspc rule -a 'Steam:Steam:Steam'        state=tiled
bspc rule -a 'Bar:lemonbar'             layer=below


# -- Cmds --

bspc config -m primary bottom_padding "$(( $(bspc config -m primary bottom_padding) + 3 ))"
bspc config -m primary bottom_monocle_padding "$(( $(bspc config -m primary bottom_monocle_padding) + 3 ))"
bspwm-panel "$(bspc query -M -m primary --names)" &

killall --user "$USER" -USR1 sxhkd || {
	sxhkd -m -1 &
}
killall --user "$USER" -USR1 picom || {
	picom --config "$XDG_CONFIG_HOME/bspwm/picom.conf" &
}

