
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?* ; do
		[ -x "$f" ] && . $f
	done
fi

for f in  $XDG_CONFIG_HOME/X11/xinitrc.d/?*; do
	. $f
done
unset $f

# -- Launch Applications --
{
	sleep 3
	$BROWSER &
	$TERMINAL -c ncmpcpp    -e ncmpcpp &
	$TERMINAL -c neomutt    -e neomutt &
	$TERMINAL -c calcurse   -e calcurse &
	$TERMINAL -c newsboat   -e newsboat &
} &


exec wm

# vim:ft=sh
