font=            CascadiaCodeNF:style=SemiLight:size=13:fontfeatures=ss19
font-bold=       Cascadia Code NF:style=SemiBold:size=13:fontfeatures=ss19
font-italic=     Cascadia Code NF:style=SemiLight Italic:size=13:fontfeatures=ss19:fontfeatures=ss01
font-bold-italic=Cascadia Code NF:style=SemiBold Italic:size=13:fontfeatures=ss19:fontfeatures=ss01

underline-offset=1

initial-color-theme=light
include=~/.config/foot/themes/gruvbox.ini

[security]
# osc52=enabled  # disabled|copy-enabled|paste-enabled|enabled

[desktop-notifications]
command=:

[bell]
visual=yes

[tweak]
font-monospace-warn=no
