--PAQ('ray-x/lsp_signature.nvim')
--
--if not PREQUIRE('lsp_signature') then
--	return
--end
--
--vim.api.nvim_create_autocmd('LspAttach', {
--	group = vim.api.nvim_create_augroup('MyLspSignatureAttach', {}),
--	callback = function(args)
--		require('lsp_signature').on_attach({
--			bind = true,
--			handler_opts = {
--				border = 'double',
--			},
--		}, args.buf)
--	end,
--})
--
