#!/usr/bin/env sh

# -- General --

bspc config focused_border_color        '#076678'
bspc config active_border_color         '#83a598'
bspc config normal_border_color         '#ebdbb2'
bspc config presel_feedback_color       '#ebdbb2'

bspc config border_width                5
bspc config borderless_singleton        true

bspc config window_gap                  10
bspc config gapless_monocle             true

bspc config top_padding                 -5
bspc config left_padding                -5
bspc config bottom_padding              -5
bspc config right_padding               -5

bspc config single_monocle              true
bspc config top_monocle_padding         $(( 0 + ( - $(bspc config top_padding   ) ) ))
bspc config right_monocle_padding       $(( 0 + ( - $(bspc config right_padding ) ) ))
bspc config bottom_monocle_padding      $(( 0 + ( - $(bspc config bottom_padding) ) ))
bspc config left_monocle_padding        $(( 0 + ( - $(bspc config left_padding  ) ) ))

#bspc config automatic_scheme            spiral
bspc config initial_polarity            second_child
bspc config split_ratio                 0.46
bspc config directional_focus_tightness low
bspc config ignore_ewmh_focus           true
bspc config removal_adjustment          true

bspc config pointer_modifier            mod4
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config click_to_focus              any
bspc config pointer_motion_interval     $(( 1000/144 ))

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true

if [ "$1" -eq 0 ]; then
	bspwm-desktop-adjust
fi

# -- Rules --

# - WM_CLASS = "class", "instance"
# - WM_NAME = "title"
# bspc rule -a 'instance:class:title'

[ "$1" -eq 0 ] && bspawn rm '*'
bspc config external_rules_command      "$(which bspwm-external_rules)"

bspc rule -r '*:*'
bspc rule -a 'Pinentry'                 state=floating sticky=on
bspc rule -a 'discord'                  desktop=8
bspc rule -a 'St:mutt'                  desktop=9
bspc rule -a 'St:neomutt'               desktop=9
bspc rule -a 'St:ncmpcpp'               desktop=10
bspc rule -a 'St:calcurse'              desktop=10
bspc rule -a 'St:newsboat'              desktop=10
bspc rule -a 'Zathura'                  state=tiled
bspc rule -a 'pavucontrol'              state=floating
bspc rule -a 'Lxappearance'             state=floating rectangle=950x600+0+0 center=on
bspc rule -a 'St:scratchpad'            state=floating center=on
bspc rule -a 'St:float'                 state=floating center=on
bspc rule -a 'mpv:gl'                   border=off
bspc rule -a 'Eclipse:Eclipse'          desktop=2
bspc rule -a 'jetbrains-idea:jetbrains-idea' desktop=2
bspc rule -a 'DBeaver'                  desktop=4
bspc rule -a 'TeamSpeak 3'              desktop=8
bspc rule -a 'Signal:signal'            desktop=8
bspc rule -a 'firefox:Browser'          state=floating
bspc rule -a 'steam'                    state=floating
bspc rule -a 'steam:*:Steam'            state=tiled
bspc rule -a 'Bar:lemonbar'             layer=below


# -- Cmds --

killall --quiet --user "$USER" -USR1 sxhkd || {
	sxhkd -m -1 &
}
killall --quiet --user "$USER" -USR1 picom || {
	picom &
}

