#!/bin/zsh

# DESCRIPTION
#    Create directory and change into (mkdir + cd)
# SYNOPSIS
#    cm directory

if (( ! ARGC )); then
	builtin cd
	return
fi

(( ARGC > 1)) &&
	return 1

if [[ ! -d "$1" ]]; then
	mkdir -p -- "$1" || return
fi

builtin cd -- "$1"

