#!/usr/bin/env zsh

# Create dircolors file from $DIRCOLORS in $DIRCOLORS_STATIC

if [[ -v DIRCOLORS && -v DIRCOLORS_STATIC ]]; then
	dircolors "$DIRCOLORS" >! "$DIRCOLORS_STATIC"
else
	printf 'At least one of DIRCOLORS and DIRCOLORS_STATIC is not defined\n' >&2
	return 1
fi
