#!/bin/zsh

#autoload -Uz compinit && compinit -d $XDG_CACHE_HOME/zsh/zcompdump
#autoload -Uz colors && colors

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

zmodload -F zsh/stat b:zstat

setopt    autocd
setopt    auto_pushd
setopt    cdable_vars
setopt    pushd_silent
setopt    pushd_to_home
setopt    pushd_minus
setopt no_pushd_ignore_dups

setopt    auto_name_dirs
setopt    auto_param_keys
setopt    auto_param_slash
setopt    auto_resume
setopt no_beep
setopt no_clobber
setopt    correct
setopt no_correct_all
setopt    interactive_comments
setopt    magic_equal_subst
setopt    multios
setopt    rm_star_wait

# -- History --

setopt    append_history
setopt    hist_expire_dups_first
setopt    hist_find_no_dups
setopt    hist_ignore_all_dups
setopt    hist_ignore_dups
setopt    hist_ignore_space
setopt    hist_no_store
setopt    hist_reduce_blanks
setopt    hist_save_no_dups
setopt    hist_verify
setopt    inc_append_history
setopt    share_history


setopt    always_to_end
setopt    auto_list
setopt    extended_glob
setopt no_list_ambiguous
setopt    glob_star_short

autoload -Uz ${ZDOTDIR}/functions/*

for f in $ZDOTDIR/{zshrc.d/*,hooks/*}.zsh; do
	source "$f"
done


