#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all



# -- Keybindings --

Mod=Mod1

# - Basics -

hc keybind $Mod-Shift-q   quit
hc keybind $Mod-Control-q reload


# focusing clients
hc keybind $Mod-s          focus left
hc keybind $Mod-n          focus down
hc keybind $Mod-r          focus up
hc keybind $Mod-t          focus right
                           

# moving clients           
hc keybind $Mod-Shift-s    shift left
hc keybind $Mod-Shift-n    shift down
hc keybind $Mod-Shift-r    shift up
hc keybind $Mod-Shift-t    shift right
                           

# resizing frames          
resizestep=0.05            
hc keybind $Mod-Control-s  resize left  +$resizestep
hc keybind $Mod-Control-n  resize down  +$resizestep
hc keybind $Mod-Control-r  resize up    +$resizestep
hc keybind $Mod-Control-t  resize right +$resizestep


# splitting frames
hc keybind $Mod-u          split left    0.5
hc keybind $Mod-i          split top     0.5
hc keybind $Mod-a          split bottom  0.5
hc keybind $Mod-e          split right   0.5


# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode



# -- Navigation --

hc keybind $Mod-g           cycle_monitor
hc keybind $Mod-Shift-g     shift_to_monitor +1

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible


hc keybind $Mod-f fullscreen


hc keybind $Mod-adiaeresis close_or_remove
hc keybind $Mod-Shift-adiaeresis remove


hc keybind $Mod-Shift-space and .           \
    compare tags.focus.curframe_wcount gt 1 \
  . cycle_layout +1 max grid
hc keybind $Mod-space and .                 \
    compare tags.focus.curframe_wcount gt 1 \
  . cycle_layout +1 vertical horizontal      


# -- Mouse --

hc mouseunbind --all

hc set focus_follows_mouse 0
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize



# -- Applications --

hc keybind $Mod-Return spawn $TERMINAL

hc keybind $Mod-l spawn dmenu_run
hc keybind $Mod-x spawn sh -c "PINENTRY_USER_DATA=gtk passmenu"

# Date is set when hl is launched.
# TODO Put in script or find better solution. 
date=$(date +%Y-%m-%d_%H:%M:%S)
hc keybind Print       spawn import -window root ~/Pictures/Screenshots/$date.png
hc keybind Shift-Print spawn import ~/Pictures/Screenshots/$date.png



# -- Media Keys --

hc keybind XF86AudioPlay              spawn mpc -q toggle
hc keybind XF86AudioStop              spawn mpc -q stop
hc keybind XF86AudioNext              spawn mpc -q next
hc keybind XF86AudioPrev              spawn mpc -q prev

hc keybind XF86AudioRaiseVolume       spawn amixer -q set Master 1+
hc keybind XF86AudioLowerVolume       spawn amixer -q set Master 1-
hc keybind XF86AudioMute              spawn amixer -q set Master toggle

hc keybind Shift+XF86AudioRaiseVolume spawn mpc -q volume +1
hc keybind Shift+XF86AudioLowerVolume spawn mpc -q volume -1


# -- Appearance --

hc set wmname LG3D

hc set frame_border_width 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0
hc set always_show_frame 1
hc set default_frame_layout 1
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


hc set frame_border_active_color '#8d3000'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#cd4500' 

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc attr theme.active.color '#cd4500'
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'

hc attr theme.normal.color '#000000'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.inner_width 0
hc attr theme.floating.outer_color black
hc attr theme.floating.inner_color black
hc attr theme.background_color   '#141414'



# -- Tags --
# idx        0       1   2   3   4   5       6
tag_names=( "1:WEB" "2" "3" "4" "5" "9:KOM" "0:MISC")
tag_keys=( {1..5} 9 0 )

hc rename default "${tag_names[0]}" || true
hc set_layout horizontal
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done



# -- Layouts --



hc load ${tag_names[6]} '
(split horizontal:0.6:0
 (clients vertical:0)
 (split vertical:0.7:1
  (clients vertical:0)
  (clients vertical:0)
 )
)
'



# -- Rules --

# xprop WM_CLASS       => "instance", "class"
# xprop WM_NAME        => "title"
# xprop WM_WINDOW_ROLE => "windowrole"

hc unrule -F

hc rule focus=off

hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole|st-256color)' focus=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class~'Pinentry.*' focus=on manage=off pseudotile=on
hc rule class='Gifview' pseudotile=on

hc rule class~'feh' focus=on

hc rule  class='Firefox' windowrole='browser' tag=${tag_names[0]}
hc rule  instance='mutt'       tag=${tag_names[5]}

hc rule  instance='ncmpcpp'    tag=${tag_names[6]} index=0
hc rule  instance='calcurse'   tag=${tag_names[6]} index=10
hc rule  instance='newsbeuter' tag=${tag_names[6]} index=11

#hc rule class='dia' windowrole='toolbox_window' index=0
#hc rule class='dia' windowrole='diagram_window' pseudotile=on index=1



# -- Misc --

# unlock, just to be sure
hc unlock

hc set tree_style '╾│ ├└╼─┐'


# -- Monitor Setup --

# hc set_monitors 1920x1080+0+0 1920x1080+1080+0
#hc set auto_detect_monitors 1
hc detect_monitors



# -- Panel --

panel=$XDG_CONFIG_HOME/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
"$panel" 0 &



